version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: skillswap-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Km15578!
      POSTGRES_DB: skillswap
    ports:
      - "5432:5432"
    volumes:
      - skillswap_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  identity-profile-service:
    build: ./identity-profile-service
    container_name: identity-profile-service
    depends_on:
      - postgres
    ports:
      - "8001:8000"

  session-service:
    build: ./session-service
    container_name: session-service
    depends_on:
      - postgres
    ports:
      - "8002:8000"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - postgres
    ports:
      - "8003:8000"

  nginx:
    image: nginx:latest
    container_name: skillswap-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - identity-profile-service
      - session-service
      - notification-service
volumes:
  skillswap_postgres_data: